src/fmbt/configs/config-mistral-7b-tgi-g5.yml, src/fmbt/utils.py
=> Adding support for default tokenizer if tokenizer is not already provided

README.md, template.yml
=> support for US-west2

template.yml
Increased time out to copy s3 bucket content
=> s3 bucket timeout template.yml

pyproject.toml, src/fmbench/scripts/deploy_w_djl_serving.py
=> Updating djl serving script, toml files

src/fmbench/configs/config-distilbert-base-uncased.yml, src/fmbench/configs/config-llama2-13b-inf2-g5-p4d-quick.yml, src/fmbench/configs/config-llama2-13b-inf2-g5-p4d-v1.yml, src/fmbench/configs/config-llama2-70b-g5-p4d-tgi.yml, src/fmbench/configs/config-llama2-70b-g5-p4d-trt.yml, src/fmbench/configs/config-llama2-70b-inf2-g5.yml, src/fmbench/configs/config-llama2-7b-g4dn-g5-trt.yml, src/fmbench/configs/config-llama2-7b-g5-quick.yml, src/fmbench/configs/config-mistral-7b-tgi-g5.yml, src/fmbench/configs/config-mistral-instruct-AWQ-p4d.yml, src/fmbench/configs/config-mistral-instruct-p4d.yml
added {region} for docker container image location
=> updated docker container support for region

template.yml
=> adding region to stack-role cft

src/fmbench/4_model_metric_analysis.ipynb
=> price per token added

src/fmbench/configs/config-llama2-13b-inf2-g5-p4d-quick.yml, src/fmbench/configs/config-llama2-13b-inf2-g5-p4d-v1.yml, src/fmbench/configs/config-llama2-70b-g5-p4d-tgi.yml, src/fmbench/configs/config-llama2-70b-g5-p4d-trt.yml
=> Updated llama chat model inf parameters and 70b djl config file

src/fmbench/configs/config-bedrock-claude.yml, src/fmbench/configs/config-bedrock.yml
=> config file updates

src/fmbench/configs/config-llama3-70b-instruct-g5-p4d.yml, src/fmbench/configs/config-llama3-8b-instruct-g5-p4d.yml, src/fmbench/prompt_template/prompt_template_llama3.txt
=> Support for Llama3 added to FMBench

src/fmbench/configs/config-mistral-7b-tgi-g5.yml, src/fmbench/configs/config-mistral-instruct-AWQ-p4d.yml, src/fmbench/configs/config-mistral-instruct-AWQ-p5-byo-ep.yml, src/fmbench/configs/config-mistral-instruct-AWQ-p5.yml, src/fmbench/configs/config-mistral-instruct-p4d.yml
=> removing the accept_eula parameter for mistral models

src/fmbench/configs/config-bedrock-llama3.yml, src/fmbench/configs/pricing.yml
=> updating config files for llama3 with comments, updating inf2 pricing

src/fmbench/configs/config-mistral-instruct-v1-p5-trtllm.yml, src/fmbench/configs/config-mistral-instruct-v2-p4d-lmi-dist.yml, src/fmbench/configs/config-mistral-instruct-v2-p4d-trtllm.yml, src/fmbench/configs/config-mistral-instruct-v2-p5-lmi-dist.yml, src/fmbench/configs/config-mistral-instruct-v2-p5-trtllm.yml
This PR contains the following config files:
1. mistral trt config files: p4d on instruct v1 & v2, p5 on instruct v2
2. mistral lmi-dist config files: p4d on instruct v2, p5 on instruct v2
=> PR for lmi-dist + trt config files on p4, p5

src/fmbench/configs/config-llama3-70b-instruct-p4d.yml, src/fmbench/configs/config-llama3-8b-instruct-p4d.yml
=> llama3 8b, 70b p4d config files

src/fmbench/configs/config-llama2-7b-g5-quick.yml
=> llama2-7b quick file with detailed comments

src/fmbench/configs/config-llama3-8b-inf2-g5.yml
=> llama3-8b-instruct inf2 config file

src/fmbench/configs/config-llama2-7b-g5-quick.yml, src/fmbench/configs/config-llama3-8b-inf2-g5.yml
=> config-file updates - llama2-7b and llama3-8b

pyproject.toml
=> add kaleido==0.2.1

pyproject.toml
=> bump up version number to v1.0.34

README.md, README_pypi.md, pyproject.toml, src/fmbench/1_generate_data.ipynb, src/fmbench/3_run_inference.ipynb, src/fmbench/4_model_metric_analysis.ipynb, src/fmbench/bring_your_own_dataset.ipynb, src/fmbench/configs/config-llama3-8b-inf2-g5-byoe-w-openorca.yml, src/fmbench/prompt_template/prompt_template_llama2_Mistral_OpenOrca.txt, src/fmbench/prompt_template/prompt_template_llama3_OpenOrca.txt
=> OpenOrca and byo dataset updates

README.md, README_pypi.md, pyproject.toml
=> bump up version for concurrency fix and instance count > 1 support

src/fmbench/configs/llama3/70b/config-bedrock-llama3.yml, src/fmbench/configs/llama3/70b/config-bedrock.yml, src/fmbench/configs/llama3/8b/config-bedrock-llama3.yml, src/fmbench/configs/llama3/8b/config-bedrock.yml
=> fix broken symlinks

src/fmbench/1_generate_data.ipynb
spelling and a period.
Documentation only.  No code change.
=> Grammar nits

src/fmbench/globals.py, src/fmbench/main.py, src/fmbench/utils.py
=> adding s3 support for local mode sm endpoints

src/fmbench/configs/llama3/8b/config-llama3-8b-inf2-24xl-tp=8-bs=4-byoe.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-inf2-48xl-tp=8-bs=4-byoe.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-trn1-32xl-tp=16-bs=4-byoe.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-trn1-32xl-tp=8-bs=4-byoe.yml
=> config fixes byoe

Dockerfile
This pull request introduces containerization for fmbench, enabling consistent and portable execution across various environments. By using Docker, a container is created that encapsulates all dependencies required to run fmbench.
Added a Dockerfile to define the container image for fmbench. The Dockerfile includes steps to:
- Set up the base image.
- Install necessary dependencies and tools.
- Copy the fmbench source code into the container.
- Set environment variables.
- Define the entry point for running fmbench.
=> Containerize FMBench

src/fmbench/configs/llama3/70b/config-ec2-llama3-70b-instruct.yml
=> Lllama3 70B on ec2

src/fmbench/configs/phi/config-phi-3-g5.yml
adding the config file for phi
=> adding phi config file

manifest.txt
=> updated manifest

src/fmbench/configs/llama2/70b/config-ec2-llama2-70b.yml
=> config file for llama 2 70B 

src/fmbench/configs/bedrock/config-bedrock-llama3-1-70b-streaming.yml, src/fmbench/configs/bedrock/config-bedrock-llama3-1-8b-streaming.yml, src/fmbench/configs/bedrock/config-bedrock-llama3-1.yml, src/fmbench/configs/pricing.yml
This contains:
1/ Config file for llama3-1-8b with streaming
2/ Config file for llama3-1-70b with streaming
3/ Updated pricing.yml file
=> adding support for llama3.1 on Amazon Bedrock

src/fmbench/scripts/neuron_deploy.py
=> updated neuron deploy code

src/fmbench/scripts/neuron_deploy.py
=> Update neuron_deploy.py with logger statements

src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g5.yml
=> config file update for llama3-8b

src/fmbench/configs/llama3/8b/config-ec2-llama3-8b-m7a-16xlarge.yml, src/fmbench/configs/pricing.yml, src/fmbench/scripts/ec2_deploy.py
This pull request introduces modifications to the `ec2_deploy.py` script to support VLLM containers with x86 CPU architecture, specifically for AMD-based EC2 instances. Additionally, it adds a new configuration file tailored for the `m7a.16xlarge` instance type for benchmarking large language models on AMD hardware. 
While the primary focus of this update is on AMD instances, Intel instances are also theoretically supported. However, further optimizations and testing are required to ensure full compatibility and optimal performance on Intel hardware before it can be confidently stated as fully supported. These enhancements enable efficient deployment of large language models on AMD instances, leveraging the specific capabilities of VLLM containers.
By submitting …
=> Deployment Support for x86 AMD CPUs on EC2

docs/benchmarking_on_ec2.md
=> add ec2 instructions to enable docker runs without sudo

src/fmbench/configs/bedrock/config-bedrock-claude.yml
=> prompt template key fix

src/fmbench/configs/llama2/7b/config-llama2-7b-g5-quick.yml
=> update llama2 7b quick file

docs/benchmarking_on_ec2.md, src/fmbench/configs/llama3/8b/config-llama3-8b-trn1-32xl-tp16-bs-4-ec2.yml
=> Contains a configuration file trn and doc fix for triton on AWS chips

src/fmbench/configs/llama3/8b/config-ec2-llama3-8b-g6e-2xlarge.yml, src/fmbench/configs/pricing.yml
=> Add support and pricing for g6e instances

src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-8-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-8-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.4xl-tp-1-mc-max-triton-ec2.yml
Add config files for 12xlarge and 24xlarge
=> Add config files for g6e instances

src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.12xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.24xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-2-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-2-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-4-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-4-mc-max-triton-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-8-mc-max-djl-ec2.yml, src/fmbench/configs/llama3/8b/config-llama3-8b-g6e.48xl-tp-8-mc-max-triton-ec2.yml
=> Add concurrency=3 for g6e instance configs

src/fmbench/configs/mixtral/config-mixtral-8x7b-g6e.48xl-ec2.yml
=> add mixtral config file for AWQ version - g6e.48xl

src/fmbench/configs/pricing.yml, src/fmbench/scripts/bedrock_predictor.py
=> pricing update + retry logic added to bedrock predictor

src/fmbench/configs/llama3.1/70b/config-ec2-llama3-1-70b-inf2-48xl-deploy-ec2-djl.yml, src/fmbench/configs/llama3.1/70b/config-ec2-llama3-1-70b-inf2-deploy-sm.yml, src/fmbench/configs/llama3.1/70b/config-ec2-llama3-1-70b-p4de.24xl-deploy-ec2-large-prompts.yml, src/fmbench/configs/llama3.1/70b/config-ec2-llama3-1-70b-p4de.24xl-deploy-ec2-longbench.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-g5.48xl-deploy-ec2.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-g6.48xl-deploy-ec2.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-g6e.24xl-deploy-ec2.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-g6e.48xl-deploy-ec2.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-inf2.48xl-deploy-ec2-triton.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-trn1.32xl-deploy-ec2-triton.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-7b-inf2.48xl-triton-ec2.yml, src/fmbench/prompt_template/prompt_template_llama3_summarization
This PR contains the config file update and prompt template update for summarization use cases. This prompt template is specifically tested on large synthetic data that is meant to be summarized as a part of the benchmarking test.
=> adding support for llama3 summarization prompt

src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-p5-djl-lmi.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g6e.12xl-djl-tp-4-mc-max-djl.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g6e.12xl-tp2-mc-max-djl.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g6e.24xl-tp2-mc-max-djl.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g6e.48xl-tp-8-djl-tp-max.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g6e.48xl-tp2-mc-max-djl.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-g6e.48xl-tp4-mc-max-djl.yml
=> All config files for llama3.1 8b on g6e instances using DJL

debug.sh, docs/benchmarking_on_ec2.md, src/fmbench/configs/llama3.1/8b/config-ec2-llama3-1-8b-g6e-2xlarge-BYOollama.yml, src/fmbench/scripts/ollama_predictor.py
This PR adds a BYO Ollama Support for FMBENCH.
This has been Tested on g6e.2xl instance, with multiple params.
=> Add BYO Ollama Support 

src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-inf2.48xl-deploy-ec2-triton.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-inf2.48xl-triton-tp24.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-70b-trn1.32xl-deploy-ec2-triton.yml, src/fmbench/configs/llama3.1/70b/config-llama3-1-7b-inf2.48xl-triton-ec2.yml
=> fix for triton ep names

src/fmbench/scripts/sagemaker_predictor.py
This PR modifies the `sagemaker_predictor.py` function to ensure that the SageMaker endpoint is deleted after inference is completed.
- Updated the `sagemaker_predictor.py` function to automatically delete the SageMaker endpoint once inference is finished.
- Tested the changes with multiple endpoint types (`ml.g5.xlarge`, `ml.g4dn.xlarge`) and a single endpoint (`ml.g5.xlarge`).
=> Update Sagemaker Predictor to delete EP

README.md, src/fmbench/configs/NousResearchHermes70B/config-Nous-Hermes3-1-70b-g5.48xl-tp-8-mc-max-djl.yml, src/fmbench/configs/NousResearchHermes70B/config-Nous-Hermes3-1-70b-inf2.48xl-triton-tp24.yml, src/fmbench/configs/NousResearchHermes70B/config-Nous-Hermes3-1-70b-trn1.32xl-deploy-ec2-triton.yml
Adding configuration for NousResearch Hermes 70B models
=> Nous Hermes configs

src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g5.2xl-tp-1-mc-max-ec2-conc-1-2.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g5.xl-tp-1-mc-max-ec2-conc-1-2.yml
=> updat workshop 

src/fmbench/configs/bedrock/config-bedrock-llama3-1-wo-evals, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g5.12xl-g5.24xl-sm.yml, src/fmbench/configs/llama3.1/8b/config-llama3.1-8b-g5.xl-g5.2xl-sm.yml
=> FMBench orchestrator bedrock + sagemaker files for llama3.1 8b 

src/fmbench/3_run_inference.ipynb, src/fmbench/scripts/ec2_predictor.py
**Issue #**  
Closes #248
**Description of changes:**  
- Updated the EC2 Metrics Table to the following format:  
- Incorporated most of the requested changes, with the following exceptions:  
1. Concurrency support is not yet added.  
2. Refactoring EC2-specific code into a separate function is still pending.  
These remaining changes will be addressed in the next PR
**Commit Confirmation:**  
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.
=> Update EC2 Metrics

src/fmbench/configs/llama3.2/1b/config-llama3.2-1b-g5.2xl-summarization-500-50.yml
This is a prompt template for summarization task for Llama-3-2-1b 
=> Summarization Prompt Template

copy_s3_content.sh, src/fmbench/configs/generic/ec2/Qwen2.5_djl.yml, src/fmbench/prompt_template/prompt_template_qwen.txt
=> qwen generic config file + prompt template

README.md, docs/simplified_config_files.md, src/fmbench/configs/bedrock/config-llama-3-3-all-models.yml, src/fmbench/configs/bedrock/config-nova-all-models.yml, src/fmbench/configs/pricing.yml, src/fmbench/configs/pricing_fallback.yml
=> Qwen + llama3.3 tests for accuracy & readme + doc updates

src/fmbench/scripts/constants.py, src/fmbench/scripts/ec2_deploy.py, src/fmbench/scripts/ec2_predictor.py, src/fmbench/scripts/inference_containers/vllm_gpu.py
This PR adds initial VLLM GPU support.
=> VLLM GPU support

template.yml
This PR contains the bug fix in the cloudformation template to avoid errors in updating the config file while sending it to the fmbench-read s3 buckets. This template.yml file is tested.
=> bug fix in the template.yml file

README.md
=> Update README.md with new python version
